SRC_URI += " \
    https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/bat-1.39.1-prel.vsix;downloadfilename=bat-1.39.1-prel.zip;name=db8ddc9c299637990f2a3073e17bbb0e3ae5773f;subdir=yarn/plugins/vscode-builtin-bat;unpack=1 \
    https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/clojure-1.39.1-prel.vsix;downloadfilename=clojure-1.39.1-prel.zip;name=dce630a4fde042a5f1788f140125f65e7c4987e7;subdir=yarn/plugins/vscode-builtin-clojure;unpack=1 \
    https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/coffeescript-1.39.1-prel.vsix;downloadfilename=coffeescript-1.39.1-prel.zip;name=23c8347c04862dffba2978f6341777ca0a0598c4;subdir=yarn/plugins/vscode-builtin-coffeescript;unpack=1 \
    https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/configuration-editing-1.39.1-prel.vsix;downloadfilename=configuration-editing-1.39.1-prel.zip;name=97ca98d61ce5628fd322aad3cf5583c69405bd2b;subdir=yarn/plugins/vscode-builtin-configuration-editing;unpack=1 \
    https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/cpp-1.39.1-prel.vsix;downloadfilename=cpp-1.39.1-prel.zip;name=f01990f126138a203684745b86a050c8e464bcec;subdir=yarn/plugins/vscode-builtin-cpp;unpack=1 \
    https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/csharp-1.39.1-prel.vsix;downloadfilename=csharp-1.39.1-prel.zip;name=5f5980b51a0b4f55d1ed599e563631cc541d98c2;subdir=yarn/plugins/vscode-builtin-csharp;unpack=1 \
    https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/css-1.39.1-prel.vsix;downloadfilename=css-1.39.1-prel.zip;name=a325a4c081cd7d15637580cecf0c51f5a8475b33;subdir=yarn/plugins/vscode-builtin-css;unpack=1 \
    https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/debug-auto-launch-1.39.1-prel.vsix;downloadfilename=debug-auto-launch-1.39.1-prel.zip;name=9ad7d4aa6741967914f67ee60d010cfd3c4cd28d;subdir=yarn/plugins/vscode-builtin-debug-auto-launch;unpack=1 \
    https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/docker-1.39.1-prel.vsix;downloadfilename=docker-1.39.1-prel.zip;name=4c444176be82404638854b67a6974a8798f29e54;subdir=yarn/plugins/vscode-builtin-docker;unpack=1 \
    https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/emmet-1.39.1-prel.vsix;downloadfilename=emmet-1.39.1-prel.zip;name=6bc632133a1a92c80822d993027174e51c6b3d46;subdir=yarn/plugins/vscode-builtin-emmet;unpack=1 \
    https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/fsharp-1.39.1-prel.vsix;downloadfilename=fsharp-1.39.1-prel.zip;name=044b4c41fbf02c1db1da986a4edba162d916f4a7;subdir=yarn/plugins/vscode-builtin-fsharp;unpack=1 \
    https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/go-1.39.1-prel.vsix;downloadfilename=go-1.39.1-prel.zip;name=55c150d935c0ef61fa6cd0dde821ed49c739cd13;subdir=yarn/plugins/vscode-builtin-go;unpack=1 \
    https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/groovy-1.39.1-prel.vsix;downloadfilename=groovy-1.39.1-prel.zip;name=f38632999f751268752ff122b8f8d9e16b77793f;subdir=yarn/plugins/vscode-builtin-groovy;unpack=1 \
    https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/grunt-1.39.1-prel.vsix;downloadfilename=grunt-1.39.1-prel.zip;name=b698562c44c8a663f5463f434d11f8b9ba80e39b;subdir=yarn/plugins/vscode-builtin-grunt;unpack=1 \
    https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/gulp-1.39.1-prel.vsix;downloadfilename=gulp-1.39.1-prel.zip;name=5e2be331e0d4b69291cea87e56a94674357d8226;subdir=yarn/plugins/vscode-builtin-gulp;unpack=1 \
    https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/handlebars-1.39.1-prel.vsix;downloadfilename=handlebars-1.39.1-prel.zip;name=c745ee2fc5f8a29cf1c93796edd0739a71bc599a;subdir=yarn/plugins/vscode-builtin-handlebars;unpack=1 \
    https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/hlsl-1.39.1-prel.vsix;downloadfilename=hlsl-1.39.1-prel.zip;name=591e5330fa719397f1701db6e5232fbbce3c2f9c;subdir=yarn/plugins/vscode-builtin-hlsl;unpack=1 \
    https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/html-1.39.1-prel.vsix;downloadfilename=html-1.39.1-prel.zip;name=b63fe9835c787286e8454ffd9dd1796b2dfc2dd9;subdir=yarn/plugins/vscode-builtin-html;unpack=1 \
    https://open-vsx.org/api/vscode/html-language-features/1.49.0/file/vscode.html-language-features-1.49.0.vsix;downloadfilename=vscode.html-language-features-1.49.0.zip;name=602bf1a735f345320ed4fd19749d2358aa69ebe5;subdir=yarn/plugins/vscode-builtin-html-language-features;unpack=1 \
    https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/ini-1.39.1-prel.vsix;downloadfilename=ini-1.39.1-prel.zip;name=cf71eb386bef1eaceb2ff0e9cab00cc3cc7a13db;subdir=yarn/plugins/vscode-builtin-ini;unpack=1 \
    https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/jake-1.39.1-prel.vsix;downloadfilename=jake-1.39.1-prel.zip;name=6e2bae9e58cce782b2a9c998c42bb51185c04abc;subdir=yarn/plugins/vscode-builtin-jake;unpack=1 \
    https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/java-1.39.1-prel.vsix;downloadfilename=java-1.39.1-prel.zip;name=b92a1fd8868d05c9fdc1a14be17cb715645599d3;subdir=yarn/plugins/vscode-builtin-java;unpack=1 \
    https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/javascript-1.39.1-prel.vsix;downloadfilename=javascript-1.39.1-prel.zip;name=9cdb811265ef1976d8ce7649c7b6eb83fbcb00be;subdir=yarn/plugins/vscode-builtin-javascript;unpack=1 \
    https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/json-1.39.1-prel.vsix;downloadfilename=json-1.39.1-prel.zip;name=ff1b2220319c0fe52afba16964c4830fe6bbd1a5;subdir=yarn/plugins/vscode-builtin-json;unpack=1 \
    https://open-vsx.org/api/vscode/json-language-features/1.46.1/file/vscode.json-language-features-1.46.1.vsix;downloadfilename=vscode.json-language-features-1.46.1.zip;name=0c59cceeb338f355c752db7535d988242d09cf0c;subdir=yarn/plugins/vscode-builtin-json-language-features;unpack=1 \
    https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/less-1.39.1-prel.vsix;downloadfilename=less-1.39.1-prel.zip;name=fbee396867bec4d70a424f052d61924e318fd9de;subdir=yarn/plugins/vscode-builtin-less;unpack=1 \
    https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/log-1.39.1-prel.vsix;downloadfilename=log-1.39.1-prel.zip;name=0ab02e9d549510fb31cc781a71641b27f169754a;subdir=yarn/plugins/vscode-builtin-log;unpack=1 \
    https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/lua-1.39.1-prel.vsix;downloadfilename=lua-1.39.1-prel.zip;name=4ad6d35896dbdd19c2424138965e1c8ed1b48208;subdir=yarn/plugins/vscode-builtin-lua;unpack=1 \
    https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/make-1.39.1-prel.vsix;downloadfilename=make-1.39.1-prel.zip;name=ebb3a5f942d993f9be6da3fb74f31c204266d724;subdir=yarn/plugins/vscode-builtin-make;unpack=1 \
    https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/markdown-1.39.1-prel.vsix;downloadfilename=markdown-1.39.1-prel.zip;name=84772b15da0594452c1c5ac417ce167466677623;subdir=yarn/plugins/vscode-builtin-markdown;unpack=1 \
    https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/merge-conflict-1.39.1-prel.vsix;downloadfilename=merge-conflict-1.39.1-prel.zip;name=18dafd62a00454a685834b28be423c2c4dbf4f89;subdir=yarn/plugins/vscode-builtin-merge-conflicts;unpack=1 \
    https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/npm-1.39.1-prel.vsix;downloadfilename=npm-1.39.1-prel.zip;name=fdcab3dbdf8dee510847b2d4ee83113c1e27e608;subdir=yarn/plugins/vscode-builtin-npm;unpack=1 \
    https://github.com/theia-ide/vscode-node-debug/releases/download/v1.35.3/node-debug-1.35.3.vsix;downloadfilename=node-debug-1.35.3.zip;name=66159f7c42ee874138af823081f1614dc3bc14c1;subdir=yarn/plugins/vscode-builtin-node-debug;unpack=1 \
    https://github.com/theia-ide/vscode-node-debug2/releases/download/v1.33.0/node-debug2-1.33.0.vsix;downloadfilename=node-debug2-1.33.0.zip;name=c0c20298ac6093b383f492657290446b54ccde6c;subdir=yarn/plugins/vscode-builtin-node-debug2;unpack=1 \
    https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/objective-c-1.39.1-prel.vsix;downloadfilename=objective-c-1.39.1-prel.zip;name=ba40e45cc2ccd0d00b67e8afb900abeb5d64f254;subdir=yarn/plugins/vscode-builtin-objective-c;unpack=1 \
    https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/perl-1.39.1-prel.vsix;downloadfilename=perl-1.39.1-prel.zip;name=41ae05cdbf4fb51d9ad08d4d299196e59900b6fd;subdir=yarn/plugins/vscode-builtin-perl;unpack=1 \
    https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/powershell-1.39.1-prel.vsix;downloadfilename=powershell-1.39.1-prel.zip;name=5215de93bb20d5140761bcec7ea8ffa3f0cadb98;subdir=yarn/plugins/vscode-builtin-powershell;unpack=1 \
    https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/pug-1.39.1-prel.vsix;downloadfilename=pug-1.39.1-prel.zip;name=49fdc613369e7082e698446143ec255dbb4aaf09;subdir=yarn/plugins/vscode-builtin-pug;unpack=1 \
    https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/python-1.39.1-prel.vsix;downloadfilename=python-1.39.1-prel.zip;name=ac31345fab8b99e19199702b4292b7a252659286;subdir=yarn/plugins/vscode-builtin-python;unpack=1 \
    https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/r-1.39.1-prel.vsix;downloadfilename=r-1.39.1-prel.zip;name=bf33031a862e7676745c196b09a2c80395319614;subdir=yarn/plugins/vscode-builtin-r;unpack=1 \
    https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/razor-1.39.1-prel.vsix;downloadfilename=razor-1.39.1-prel.zip;name=c3c44aec7f1dc771deabcc789c510fc85fd7ee9d;subdir=yarn/plugins/vscode-builtin-razor;unpack=1 \
    https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/ruby-1.39.1-prel.vsix;downloadfilename=ruby-1.39.1-prel.zip;name=c226d17be47ea4372fe3c845785853993649e549;subdir=yarn/plugins/vscode-builtin-ruby;unpack=1 \
    https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/rust-1.39.1-prel.vsix;downloadfilename=rust-1.39.1-prel.zip;name=d7ee390c1579362e3bdefc5366dd783535eb5147;subdir=yarn/plugins/vscode-builtin-rust;unpack=1 \
    https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/scss-1.39.1-prel.vsix;downloadfilename=scss-1.39.1-prel.zip;name=38d6a72bef5b0baea7af1bd4c71896c9859b487b;subdir=yarn/plugins/vscode-builtin-scss;unpack=1 \
    https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/shaderlab-1.39.1-prel.vsix;downloadfilename=shaderlab-1.39.1-prel.zip;name=b7b56209ef716c09c3aea70cc5dfb9b145027c29;subdir=yarn/plugins/vscode-builtin-shaderlab;unpack=1 \
    https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/shellscript-1.39.1-prel.vsix;downloadfilename=shellscript-1.39.1-prel.zip;name=65607c312cb9dacb30fbf8de9579c013effa9d36;subdir=yarn/plugins/vscode-builtin-shellscript;unpack=1 \
    https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/sql-1.39.1-prel.vsix;downloadfilename=sql-1.39.1-prel.zip;name=7be3ac980a2069bcadeac49bf385a6319f20694e;subdir=yarn/plugins/vscode-builtin-sql;unpack=1 \
    https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/swift-1.39.1-prel.vsix;downloadfilename=swift-1.39.1-prel.zip;name=12442009a7c89d670a1f8858f17c8b5da6936e87;subdir=yarn/plugins/vscode-builtin-swift;unpack=1 \
    https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/theme-abyss-1.39.1-prel.vsix;downloadfilename=theme-abyss-1.39.1-prel.zip;name=2a8bc2231dfbaacee0c297441362deb5eb7fefba;subdir=yarn/plugins/vscode-builtin-theme-abyss;unpack=1 \
    https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/theme-defaults-1.39.1-prel.vsix;downloadfilename=theme-defaults-1.39.1-prel.zip;name=f5b8402cdb6d8d0943d57914fec19f52bd72b0d3;subdir=yarn/plugins/vscode-builtin-theme-defaults;unpack=1 \
    https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/theme-kimbie-dark-1.39.1-prel.vsix;downloadfilename=theme-kimbie-dark-1.39.1-prel.zip;name=bfef8bb6821430dd98abbeef23bfbcba7eb24082;subdir=yarn/plugins/vscode-builtin-theme-kimbie-dark;unpack=1 \
    https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/theme-monokai-1.39.1-prel.vsix;downloadfilename=theme-monokai-1.39.1-prel.zip;name=b285947b1bea55236a77684039e88894a9952ada;subdir=yarn/plugins/vscode-builtin-theme-monokai;unpack=1 \
    https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/theme-monokai-dimmed-1.39.1-prel.vsix;downloadfilename=theme-monokai-dimmed-1.39.1-prel.zip;name=7eb5be3e43e909efa6faaa354380703a766df229;subdir=yarn/plugins/vscode-builtin-theme-dimmed;unpack=1 \
    https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/theme-quietlight-1.39.1-prel.vsix;downloadfilename=theme-quietlight-1.39.1-prel.zip;name=4f859d557df4ab1654c6690d5667f1e3a6345086;subdir=yarn/plugins/vscode-builtin-theme-quietlight;unpack=1 \
    https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/theme-red-1.39.1-prel.vsix;downloadfilename=theme-red-1.39.1-prel.zip;name=b2c9bb8b0bcf4ff7b4eb35fc7f735c2d41887c92;subdir=yarn/plugins/vscode-builtin-theme-red;unpack=1 \
    https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/theme-solarized-dark-1.39.1-prel.vsix;downloadfilename=theme-solarized-dark-1.39.1-prel.zip;name=eae84c907083281bbd1b06df86cc5fe5b73b7a97;subdir=yarn/plugins/vscode-builtin-theme-solarized-dark;unpack=1 \
    https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/theme-tomorrow-night-blue-1.39.1-prel.vsix;downloadfilename=theme-tomorrow-night-blue-1.39.1-prel.zip;name=949ada420cd335c8203b142a6ee5e8b90e327483;subdir=yarn/plugins/vscode-builtin-theme-tomorrow-night-blue;unpack=1 \
    https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/typescript-1.39.1-prel.vsix;downloadfilename=typescript-1.39.1-prel.zip;name=e8c284877150feff8a50e514eef5df9d0d73eda2;subdir=yarn/plugins/vscode-builtin-typescript;unpack=1 \
    https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/typescript-language-features-1.39.1-prel.vsix;downloadfilename=typescript-language-features-1.39.1-prel.zip;name=850a1bfd85654496d6636f17b182bce2deea92a5;subdir=yarn/plugins/vscode-builtin-typescript-language-features;unpack=1 \
    https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/vb-1.39.1-prel.vsix;downloadfilename=vb-1.39.1-prel.zip;name=c0470bbe1fa58a573b3044697c486d0a6574a1f9;subdir=yarn/plugins/vscode-builtin-vb;unpack=1 \
    https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/vscode-theme-seti-1.39.1-prel.vsix;downloadfilename=vscode-theme-seti-1.39.1-prel.zip;name=6687fcec8b99c28d13025fd07c44e5738fe50756;subdir=yarn/plugins/vscode-builtin-icon-theme-seti;unpack=1 \
    https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/xml-1.39.1-prel.vsix;downloadfilename=xml-1.39.1-prel.zip;name=a881ef4cbabdebc62b4517ca411ebc4ded900596;subdir=yarn/plugins/vscode-builtin-xml;unpack=1 \
    https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/yaml-1.39.1-prel.vsix;downloadfilename=yaml-1.39.1-prel.zip;name=ee61b366d3cfb3ec248e656546d7795beba58ae6;subdir=yarn/plugins/vscode-builtin-yaml;unpack=1 \
    https://github.com/theia-ide/editorconfig-vscode/releases/download/v0.14.4/EditorConfig-0.14.4.vsix;downloadfilename=EditorConfig-0.14.4.zip;name=611a3f2d98544ad8442bfae50f159126cbb22ca3;subdir=yarn/plugins/vscode-editorconfig;unpack=1 \
    https://open-vsx.org/api/ms-python/python/2020.8.105369/file/ms-python.python-2020.8.105369.vsix;downloadfilename=ms-python.python-2020.8.105369.zip;name=a9b7c9e1bfb4fb82f0ced2313b6f53904f7e0d31;subdir=yarn/plugins/vscode-python;unpack=1 \
"

SRC_URI[db8ddc9c299637990f2a3073e17bbb0e3ae5773f.sha1sum] = "db8ddc9c299637990f2a3073e17bbb0e3ae5773f"
SRC_URI[dce630a4fde042a5f1788f140125f65e7c4987e7.sha1sum] = "dce630a4fde042a5f1788f140125f65e7c4987e7"
SRC_URI[23c8347c04862dffba2978f6341777ca0a0598c4.sha1sum] = "23c8347c04862dffba2978f6341777ca0a0598c4"
SRC_URI[97ca98d61ce5628fd322aad3cf5583c69405bd2b.sha1sum] = "97ca98d61ce5628fd322aad3cf5583c69405bd2b"
SRC_URI[f01990f126138a203684745b86a050c8e464bcec.sha1sum] = "f01990f126138a203684745b86a050c8e464bcec"
SRC_URI[5f5980b51a0b4f55d1ed599e563631cc541d98c2.sha1sum] = "5f5980b51a0b4f55d1ed599e563631cc541d98c2"
SRC_URI[a325a4c081cd7d15637580cecf0c51f5a8475b33.sha1sum] = "a325a4c081cd7d15637580cecf0c51f5a8475b33"
SRC_URI[9ad7d4aa6741967914f67ee60d010cfd3c4cd28d.sha1sum] = "9ad7d4aa6741967914f67ee60d010cfd3c4cd28d"
SRC_URI[4c444176be82404638854b67a6974a8798f29e54.sha1sum] = "4c444176be82404638854b67a6974a8798f29e54"
SRC_URI[6bc632133a1a92c80822d993027174e51c6b3d46.sha1sum] = "6bc632133a1a92c80822d993027174e51c6b3d46"
SRC_URI[044b4c41fbf02c1db1da986a4edba162d916f4a7.sha1sum] = "044b4c41fbf02c1db1da986a4edba162d916f4a7"
SRC_URI[55c150d935c0ef61fa6cd0dde821ed49c739cd13.sha1sum] = "55c150d935c0ef61fa6cd0dde821ed49c739cd13"
SRC_URI[f38632999f751268752ff122b8f8d9e16b77793f.sha1sum] = "f38632999f751268752ff122b8f8d9e16b77793f"
SRC_URI[b698562c44c8a663f5463f434d11f8b9ba80e39b.sha1sum] = "b698562c44c8a663f5463f434d11f8b9ba80e39b"
SRC_URI[5e2be331e0d4b69291cea87e56a94674357d8226.sha1sum] = "5e2be331e0d4b69291cea87e56a94674357d8226"
SRC_URI[c745ee2fc5f8a29cf1c93796edd0739a71bc599a.sha1sum] = "c745ee2fc5f8a29cf1c93796edd0739a71bc599a"
SRC_URI[591e5330fa719397f1701db6e5232fbbce3c2f9c.sha1sum] = "591e5330fa719397f1701db6e5232fbbce3c2f9c"
SRC_URI[b63fe9835c787286e8454ffd9dd1796b2dfc2dd9.sha1sum] = "b63fe9835c787286e8454ffd9dd1796b2dfc2dd9"
SRC_URI[602bf1a735f345320ed4fd19749d2358aa69ebe5.sha1sum] = "602bf1a735f345320ed4fd19749d2358aa69ebe5"
SRC_URI[cf71eb386bef1eaceb2ff0e9cab00cc3cc7a13db.sha1sum] = "cf71eb386bef1eaceb2ff0e9cab00cc3cc7a13db"
SRC_URI[6e2bae9e58cce782b2a9c998c42bb51185c04abc.sha1sum] = "6e2bae9e58cce782b2a9c998c42bb51185c04abc"
SRC_URI[b92a1fd8868d05c9fdc1a14be17cb715645599d3.sha1sum] = "b92a1fd8868d05c9fdc1a14be17cb715645599d3"
SRC_URI[9cdb811265ef1976d8ce7649c7b6eb83fbcb00be.sha1sum] = "9cdb811265ef1976d8ce7649c7b6eb83fbcb00be"
SRC_URI[ff1b2220319c0fe52afba16964c4830fe6bbd1a5.sha1sum] = "ff1b2220319c0fe52afba16964c4830fe6bbd1a5"
SRC_URI[0c59cceeb338f355c752db7535d988242d09cf0c.sha1sum] = "0c59cceeb338f355c752db7535d988242d09cf0c"
SRC_URI[fbee396867bec4d70a424f052d61924e318fd9de.sha1sum] = "fbee396867bec4d70a424f052d61924e318fd9de"
SRC_URI[0ab02e9d549510fb31cc781a71641b27f169754a.sha1sum] = "0ab02e9d549510fb31cc781a71641b27f169754a"
SRC_URI[4ad6d35896dbdd19c2424138965e1c8ed1b48208.sha1sum] = "4ad6d35896dbdd19c2424138965e1c8ed1b48208"
SRC_URI[ebb3a5f942d993f9be6da3fb74f31c204266d724.sha1sum] = "ebb3a5f942d993f9be6da3fb74f31c204266d724"
SRC_URI[84772b15da0594452c1c5ac417ce167466677623.sha1sum] = "84772b15da0594452c1c5ac417ce167466677623"
SRC_URI[18dafd62a00454a685834b28be423c2c4dbf4f89.sha1sum] = "18dafd62a00454a685834b28be423c2c4dbf4f89"
SRC_URI[fdcab3dbdf8dee510847b2d4ee83113c1e27e608.sha1sum] = "fdcab3dbdf8dee510847b2d4ee83113c1e27e608"
SRC_URI[66159f7c42ee874138af823081f1614dc3bc14c1.sha1sum] = "66159f7c42ee874138af823081f1614dc3bc14c1"
SRC_URI[c0c20298ac6093b383f492657290446b54ccde6c.sha1sum] = "c0c20298ac6093b383f492657290446b54ccde6c"
SRC_URI[ba40e45cc2ccd0d00b67e8afb900abeb5d64f254.sha1sum] = "ba40e45cc2ccd0d00b67e8afb900abeb5d64f254"
SRC_URI[41ae05cdbf4fb51d9ad08d4d299196e59900b6fd.sha1sum] = "41ae05cdbf4fb51d9ad08d4d299196e59900b6fd"
SRC_URI[5215de93bb20d5140761bcec7ea8ffa3f0cadb98.sha1sum] = "5215de93bb20d5140761bcec7ea8ffa3f0cadb98"
SRC_URI[49fdc613369e7082e698446143ec255dbb4aaf09.sha1sum] = "49fdc613369e7082e698446143ec255dbb4aaf09"
SRC_URI[ac31345fab8b99e19199702b4292b7a252659286.sha1sum] = "ac31345fab8b99e19199702b4292b7a252659286"
SRC_URI[bf33031a862e7676745c196b09a2c80395319614.sha1sum] = "bf33031a862e7676745c196b09a2c80395319614"
SRC_URI[c3c44aec7f1dc771deabcc789c510fc85fd7ee9d.sha1sum] = "c3c44aec7f1dc771deabcc789c510fc85fd7ee9d"
SRC_URI[c226d17be47ea4372fe3c845785853993649e549.sha1sum] = "c226d17be47ea4372fe3c845785853993649e549"
SRC_URI[d7ee390c1579362e3bdefc5366dd783535eb5147.sha1sum] = "d7ee390c1579362e3bdefc5366dd783535eb5147"
SRC_URI[38d6a72bef5b0baea7af1bd4c71896c9859b487b.sha1sum] = "38d6a72bef5b0baea7af1bd4c71896c9859b487b"
SRC_URI[b7b56209ef716c09c3aea70cc5dfb9b145027c29.sha1sum] = "b7b56209ef716c09c3aea70cc5dfb9b145027c29"
SRC_URI[65607c312cb9dacb30fbf8de9579c013effa9d36.sha1sum] = "65607c312cb9dacb30fbf8de9579c013effa9d36"
SRC_URI[7be3ac980a2069bcadeac49bf385a6319f20694e.sha1sum] = "7be3ac980a2069bcadeac49bf385a6319f20694e"
SRC_URI[12442009a7c89d670a1f8858f17c8b5da6936e87.sha1sum] = "12442009a7c89d670a1f8858f17c8b5da6936e87"
SRC_URI[2a8bc2231dfbaacee0c297441362deb5eb7fefba.sha1sum] = "2a8bc2231dfbaacee0c297441362deb5eb7fefba"
SRC_URI[f5b8402cdb6d8d0943d57914fec19f52bd72b0d3.sha1sum] = "f5b8402cdb6d8d0943d57914fec19f52bd72b0d3"
SRC_URI[bfef8bb6821430dd98abbeef23bfbcba7eb24082.sha1sum] = "bfef8bb6821430dd98abbeef23bfbcba7eb24082"
SRC_URI[b285947b1bea55236a77684039e88894a9952ada.sha1sum] = "b285947b1bea55236a77684039e88894a9952ada"
SRC_URI[7eb5be3e43e909efa6faaa354380703a766df229.sha1sum] = "7eb5be3e43e909efa6faaa354380703a766df229"
SRC_URI[4f859d557df4ab1654c6690d5667f1e3a6345086.sha1sum] = "4f859d557df4ab1654c6690d5667f1e3a6345086"
SRC_URI[b2c9bb8b0bcf4ff7b4eb35fc7f735c2d41887c92.sha1sum] = "b2c9bb8b0bcf4ff7b4eb35fc7f735c2d41887c92"
SRC_URI[eae84c907083281bbd1b06df86cc5fe5b73b7a97.sha1sum] = "eae84c907083281bbd1b06df86cc5fe5b73b7a97"
SRC_URI[949ada420cd335c8203b142a6ee5e8b90e327483.sha1sum] = "949ada420cd335c8203b142a6ee5e8b90e327483"
SRC_URI[e8c284877150feff8a50e514eef5df9d0d73eda2.sha1sum] = "e8c284877150feff8a50e514eef5df9d0d73eda2"
SRC_URI[850a1bfd85654496d6636f17b182bce2deea92a5.sha1sum] = "850a1bfd85654496d6636f17b182bce2deea92a5"
SRC_URI[c0470bbe1fa58a573b3044697c486d0a6574a1f9.sha1sum] = "c0470bbe1fa58a573b3044697c486d0a6574a1f9"
SRC_URI[6687fcec8b99c28d13025fd07c44e5738fe50756.sha1sum] = "6687fcec8b99c28d13025fd07c44e5738fe50756"
SRC_URI[a881ef4cbabdebc62b4517ca411ebc4ded900596.sha1sum] = "a881ef4cbabdebc62b4517ca411ebc4ded900596"
SRC_URI[ee61b366d3cfb3ec248e656546d7795beba58ae6.sha1sum] = "ee61b366d3cfb3ec248e656546d7795beba58ae6"
SRC_URI[611a3f2d98544ad8442bfae50f159126cbb22ca3.sha1sum] = "611a3f2d98544ad8442bfae50f159126cbb22ca3"
SRC_URI[a9b7c9e1bfb4fb82f0ced2313b6f53904f7e0d31.sha1sum] = "a9b7c9e1bfb4fb82f0ced2313b6f53904f7e0d31"

